# Generated by Django 5.1 on 2024-09-03 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_list', '0002_alter_recipemodel_complexity'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipemodel',
            name='count_view',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
