# Generated by Django 5.1 on 2024-09-03 12:50

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_list', '0003_recipemodel_count_view'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipemodel',
            name='text_recipe',
            field=tinymce.models.HTMLField(),
        ),
    ]
