# Generated by Django 5.1 on 2024-10-09 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_list', '0007_savedrecipemodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipemodel',
            name='image',
        ),
        migrations.AddField(
            model_name='recipemodel',
            name='image_url',
            field=models.CharField(blank=True),
        ),
    ]
